Be 10 - payment method
colegio-bilingue-cv/cb-api pull request #21
Opened 2022-09-28 02:55 UTC by Usuca

2022-09-29 01:39 UTC, cumanachao requested changes

2022-09-29 01:39 UTC, cumanachao commented on app/controllers/api/payment_methods_controller.rb
> +    payment_method= PaymentMethod.all
Espacio antes del =

2022-09-29 01:39 UTC, cumanachao commented on app/controllers/api/payment_methods_controller.rb
> +
Remover espacio

2022-09-29 01:39 UTC, cumanachao commented on app/controllers/api/payment_methods_controller.rb
> +    payment_method= PaymentMethod.create!(payment_method_params)
Espacio antes del =

2022-09-29 01:39 UTC, cumanachao commented on app/controllers/api/payment_methods_controller.rb
> +end
Agregar línea en blanco al final del archivo

2022-09-29 01:39 UTC, cumanachao commented on app/controllers/api/student_payment_methods_controller.rb
> +
Sacar esta líneas.

2022-09-29 01:39 UTC, cumanachao commented on app/controllers/api/student_payment_methods_controller.rb
> +    student_payment_method= StudentPaymentMethod.new(student_payment_method_params)
Reemplazar por `student_payment_method= StudentPaymentMethod.create!(student_payment_method_params)`

O sea, estas asignando básicamente todos los valores del params a mano

2022-09-29 01:39 UTC, cumanachao commented on app/controllers/api/students_controller.rb
> +  #rescue ActiveRecord::RecordNotFound
Comentado?

2022-09-29 01:39 UTC, cumanachao commented on app/controllers/api/students_controller.rb
>  end
Agregar línea la final del archivo

2022-09-29 01:39 UTC, cumanachao commented on app/models/payment_method.rb
> +    has_many :student_payment_methods
Indentar con 2 espacios solamente

2022-09-29 01:39 UTC, cumanachao commented on app/models/payment_method.rb
> +    validates :method, presence: true , uniqueness: true
Sacar espacio antes de la `,`

2022-09-29 01:39 UTC, cumanachao commented on app/controllers/api/students_controller.rb
> +        student_payment_methods: Panko::ArraySerializer.new(student_payment_methods, each_serializer: StudentPaymentMethodSerializer)
Yo capaz lo que haría es ponerle como nombre a la key del json `payment_methods`, usar el serializer de `StudentPaymentMethod` le pondría los datos del estudiante y del payment method. Así no es una respuesta con ids pelados nomás

2022-09-29 01:39 UTC, cumanachao commented on app/models/student_payment_method.rb
> +    belongs_to :student
Idem indentación

2022-09-29 01:39 UTC, cumanachao commented on app/models/student_payment_method.rb
> +    validates :year, :student_id, :payment_method_id, presence: true
Desde Rails 5, todas las asociaciones `belongs_to` son obligatorias, a menos que tenga `optional: true`.
Es decir, no es necesario validar los ids a mano.

Probá cambiar eso y crear en la consola de Rails un par para ver cómo funciona bien.

2022-09-29 01:39 UTC, cumanachao commented on app/serializers/payment_method_serializer.rb
> +  attributes :id, :method
Vale el comentario que puse en el controller

2022-09-29 01:39 UTC, cumanachao commented on lib/tasks/paymentMethods.rake
> +    PaymentMethod.create!(:method => "Efectivo")
Usar comillas simples siempre que se pueda y la sintaxis siguiente de Hash: `PaymentMethod.create!(method: 'Efectivo')`

2022-09-29 01:39 UTC, cumanachao commented on lib/tasks/paymentMethods.rake
> +task :generatePaymentMethods => [ :environment ] do
El nombre de la task tiene que ser en snake_case, igual que el nombre del archivo: `generate_payment_methods`

`task generate_payment_methods: :environment do`

2022-09-29 01:39 UTC, cumanachao commented on lib/tasks/paymentMethods.rake
> +    require "#{Rails.root}/app/models/payment_method.rb"
Para evitar esta línea, lo que hay que hacer es agregar esta linea en el archivo `config/application.rb`:
`config.eager_load_paths << Rails.root.join('lib').to_path`

2022-09-29 23:44 UTC, cumanachao requested changes

2022-09-29 23:44 UTC, cumanachao commented on app/models/payment_method.rb
> +class PaymentMethod < ApplicationRecord
Sacar los espacios al final del nombre de la clase

2022-09-29 23:44 UTC, cumanachao commented on app/controllers/api/students_controller.rb
> +   # render json: {}, status: :not_found
Este rescue está bien, descomentalo.

2022-09-29 23:44 UTC, cumanachao commented on lib/tasks/generate_payment_method.rake
> +    require "#{Rails.root}/app/models/payment_method.rb"
Acordate de agregar la línea que puse en el comentario anterior en el archivo `config/application.rb` y así poder sacar esta linea de la task

2022-09-29 23:44 UTC, cumanachao commented on lib/tasks/generate_payment_method.rake
> +    PaymentMethod.create!(method: "Financiación")
Cambiar por comillas simples también.

2022-09-30 03:46 UTC, Usuca commented
Creo que me falta en rspec probar crear un payment_method y el get payment_method del controlador del studiante.

2022-10-01 01:31 UTC, cumanachao approved these changes

2022-10-01 01:34 UTC, merged