BE-19: Crear endpoint para la modificación de métodos de pago.
colegio-bilingue-cv/cb-api pull request #30
Opened 2022-10-10 23:44 UTC by Usuca

2022-10-13 01:20 UTC, cumanachao requested changes

2022-10-13 01:20 UTC, cumanachao commented on app/controllers/api/payment_methods_controller.rb
> +    params.require(:payment_method).permit(:method, :id)
Por qué esto? No debería se pasa el id del payment method adentro del json

2022-10-13 01:20 UTC, cumanachao commented on app/controllers/api/student_payment_methods_controller.rb
> +    params.require(:student_payment_method).permit(:id, :year, :payment_method_id, :student_id)
Idem acá

2022-10-13 01:20 UTC, cumanachao commented on app/controllers/api/student_payment_methods_controller.rb
> +  rescue ActiveRecord::RecordNotUnique
Esto no debería salir nunca porque la columna id no se tiene que poder modificar por endpoints

2022-10-13 01:20 UTC, cumanachao commented on spec/controllers/api/student_payment_methods_controller_spec.rb
> +    let(:student_payment_method_attrs){ student_payment_method.attributes }
Espacio antes de {

2022-10-13 01:20 UTC, cumanachao commented on spec/controllers/api/student_payment_methods_controller_spec.rb
> +          { student_payment_method:{year: Date.yesterday,
Espacio entre `:` y `{`

2022-10-13 01:20 UTC, cumanachao commented on spec/controllers/api/student_payment_methods_controller_spec.rb
> +    end
Línea en blanco después del end; ojo indentación

2022-10-13 01:20 UTC, cumanachao commented on spec/models/student_payment_method_spec.rb
> +      it { should validate_presence_of(:year)}
Espacios en blanco extra

2022-10-13 02:49 UTC, Usuca commented on app/controllers/api/student_payment_methods_controller.rb
> +  rescue ActiveRecord::RecordNotUnique
Este lo agregue por si ponen ( id_student, id_payment_method ,  year) repetido

2022-10-14 00:58 UTC, cumanachao commented on app/controllers/api/student_payment_methods_controller.rb
> +  rescue ActiveRecord::RecordNotUnique
Bien entonces tenés que retornar un mensaje de error acorde. Fijate cómo hice en el el base controller para manejar los otros y crear los mensajes de error acordes

2022-10-15 01:16 UTC, cumanachao approved these changes

2022-10-15 01:18 UTC, merged