BE-21 adds 'update' method to type_scholarship and student_type_scholarship
colegio-bilingue-cv/cb-api pull request #32
Opened 2022-10-12 23:04 UTC by Chuardo

2022-10-13 01:39 UTC, cumanachao requested changes

2022-10-13 01:39 UTC, cumanachao commented on app/controllers/api/student_type_scholarships_controller.rb
> +    params.require(:student_type_scholarship).permit(:id, :student_id, :type_scholarship_id)
Por qué editar el id? no debería estar esto acá

2022-10-13 01:39 UTC, cumanachao commented on app/controllers/api/student_type_scholarships_controller.rb
> +  rescue ActiveRecord::RecordNotUnique
Esto no tiene que estar porque el id no se tiene que poder editar nunca

2022-10-13 01:39 UTC, cumanachao commented on app/controllers/api/type_scholarships_controller.rb
> +end
Falta final de linea blanca

2022-10-13 01:39 UTC, cumanachao commented on app/controllers/api/type_scholarships_controller.rb
> +    params.require(:type_scholarship).permit(:description, :scholarship, :id)
Idem lo del id

2022-10-13 01:39 UTC, cumanachao commented on app/models/student_type_scholarship.rb
> +  delegate :description, to: :type_scholarship, prefix: true
Esto se puede unir en una sola linea:
`delegate :description, :scholarship, to: :type_scholarship, prefix: true`

2022-10-13 01:39 UTC, cumanachao commented on lib/tasks/generate_type_scholarship.rake
> +end
faltsa final de linea blank

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/student_type_scholarship_controller_spec.rb
> +        let(:type_scholarship2) { FactoryBot.create(:type_scholarship) }
Cambiale el nombre por `second_type_scholarship`

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/student_type_scholarship_controller_spec.rb
> +          { student_type_scholarship:{student_id: student_type_scholarship.student_id,
Espacio después de `:` y antes de `{`

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/student_type_scholarship_controller_spec.rb
> +
Eliminar linea en blanco

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/student_type_scholarship_controller_spec.rb
> +    end
Ojo indentación

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/student_type_scholarship_controller_spec.rb
> +        { student_type_scholarship:{student_id: student_type_scholarship.student_id,
Espacio entre `:` y `{`

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/students_controller_spec.rb
> +              description: if type_scholarship.description.to_s=="" then nil else type_scholarship.description.to_s end
Esto es lo que decía con que tienen que haber dos casos diferentes. Uno con que la description sea blank y la otra sin que sea blank. No está bueno tener este tipo de ifs en los expected values

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/type_scholarships_controller_spec.rb
> +            description: if type_scholarship.description.to_s=="" then nil else type_scholarship.description.to_s end
Idem

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/type_scholarships_controller_spec.rb
> +        context 'with scholarship=:bidding and description' do
Cambiar el texto por `when scholarship is bidding`. El `and description` no sé qué significa.
Tené en cuanta que estos textos son para que sean legibles por humanos. Tiene que tener sentido la frase en idioma natural

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/type_scholarships_controller_spec.rb
> +        context 'with scholarship=:subsidized and no description' do
Idem

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/type_scholarships_controller_spec.rb
> +            }.to change(type_scholarship, :scholarship).to("agreement")
Cambia las comillas dobles por simples siempre que no tengas que interpolar strings

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/type_scholarships_controller_spec.rb
> +        its(:body) do
Falta agregar el texto de los errores

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/type_scholarships_controller_spec.rb
> +          should include_json({})
Falta agregar el texto de los errores

2022-10-13 01:39 UTC, cumanachao commented on spec/controllers/api/type_scholarships_controller_spec.rb
> +        should include_json({})
Falta agregar el texto de los errores

2022-10-13 01:39 UTC, cumanachao commented on spec/factories/type_scholarships.rb
> +    description { if scholarship==(0||2) then Faker::Lorem.sentence else nil end}
Estos tienen que ser traits diferentes. 
Por otro lado, mirá los métodos que te definen los `enum` en rails: https://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html

2022-10-13 03:03 UTC, Chuardo commented on spec/factories/type_scholarships.rb
> +    description { if scholarship==(0||2) then Faker::Lorem.sentence else nil end}
No me esta saliendo cambiarlo por algo donde no use numeros, me puse a leer la documentacion de Faker y no tiene generator dedicado a Enum

2022-10-14 00:52 UTC, cumanachao commented on spec/factories/type_scholarships.rb
> +    description { if scholarship==(0||2) then Faker::Lorem.sentence else nil end}
https://github.com/thoughtbot/factory_bot/releases/tag/v6.0.0 factory bot ya lo hace solo. Te define los traits por default

2022-10-17 15:37 UTC, cumanachao approved these changes

2022-10-17 16:38 UTC, merged