BE-22: Crear endpoint para la modificación de los descuentos de un estudiante.
colegio-bilingue-cv/cb-api pull request #35
Opened 2022-10-13 22:35 UTC by Usuca

2022-10-14 01:04 UTC, cumanachao requested changes
Fijate que se agregó un commit que no va acá

2022-10-14 01:04 UTC, cumanachao commented on app/controllers/api/discounts_controller.rb
> +    render json: {}, status: :unprocessable_entity
Esto se maneja solo. Toma como referencia el base controller

2022-10-14 01:04 UTC, cumanachao commented on app/controllers/api/family_members_controller.rb
> +    student.family_members << family_member
Estos cambios no son de este tickets

2022-10-14 01:04 UTC, cumanachao commented on spec/controllers/api/family_members_controller_spec.rb
> +      context 'with valid data and two students assigned' do
Estos cambios no son de este tickets

2022-10-14 02:24 UTC, Usuca commented on app/controllers/api/family_members_controller.rb
> +    student.family_members << family_member
ok, ya vi lo que paso, hice mal el rebase y quedo eso tambien

2022-10-15 01:26 UTC, cumanachao approved these changes

2022-10-15 01:27 UTC, merged