(3)BE-15: Crear endpoint de modificación de usuario
colegio-bilingue-cv/cb-api pull request #36
Opened 2022-10-16 00:08 UTC by Usuca

2022-10-16 00:14 UTC, Usuca commented
Esta bien que se pueda editar la contraseña y email?

2022-10-17 20:16 UTC, cumanachao requested changes

2022-10-17 20:16 UTC, cumanachao commented on db/schema.rb
> +    t.index ["cicle_id"], name: "index_cicles_questions_on_cicle_id"
Todo esto no va acá

2022-10-17 20:17 UTC, cumanachao commented
> 

Entiendo que sí

2022-10-19 00:16 UTC, cumanachao approved these changes

2022-10-19 00:17 UTC, merged