Be 151
colegio-bilingue-cv/cb-api pull request #53
Opened 2022-10-29 01:25 UTC by AnimA97

-Agrego rake task para craecion de grades, groups y cicles
-Funcionalidad de listado de docentes con su propio controllador con sus respectivos tests

2022-10-29 14:40 UTC, Usuca commented on config/routes.rb
>      end
Este va con resource sin la s para que no pida un id

2022-10-29 22:09 UTC, cumanachao requested changes

2022-10-29 22:09 UTC, cumanachao commented on app/models/user_group.rb
> +  validates :user, :group, :role_id, presence: true
User y group se validan solos porque `belongs_to` es obligatorio por default desde Rails 5

2022-10-29 22:09 UTC, cumanachao commented on app/models/user.rb
> +  end
Estos métodos están de más porque la gema rolify ya agregar scopes en los modelos que tienen `rolify`
Fijate acá: https://github.com/RolifyCommunity/rolify#class-level

2022-10-29 22:09 UTC, cumanachao commented on app/controllers/api/teachers_controller.rb
> +    teachers = User.by_role_name("teacher")
Esto sería `User.with_role(:teacher)`. Ver siguiente comentario.

2022-10-29 22:09 UTC, cumanachao commented on app/serializers/group_serializer.rb
> +  def grade
En lugar de retornar solo el nombre, agregá todo el grade con el `GradeSerializer`

https://panko.dev/docs/associations#inference

``` ruby
has_one :grade
```

2022-10-29 22:09 UTC, cumanachao commented on app/serializers/teacher_serializer.rb
> +  end
Lo mismo acá; `has_many :groups`

https://panko.dev/docs/associations#inference

2022-10-29 22:09 UTC, cumanachao commented on config/locales/devise.es.yml
> +    not_found: 'Rol no encontrado'
Esto no va acá

2022-10-29 22:09 UTC, cumanachao commented on config/routes.rb
> +    resources :teachers, only:[:index], controller: :teachers
Falta espacio después de `only:` y la key `:controller` no es necesaria porque el controller se llama igual que la ruta y Rails lo infiere solo.

2022-10-29 22:09 UTC, cumanachao commented on app/controllers/api/teachers_controller.rb
> +
Borrar espacio extra al final:
Para que no queden llíneas extra en blanco y espacios en blanco al final de las líneas activa estas tres opciones en VS Code (lo pongo en inglés porque lo tengo en inglés):
- Trim final newlines
- Trim trailing whitespaces
- Insert final Newline

2022-10-29 22:09 UTC, cumanachao commented on config/locales/es.yml
> +    not_found: 'Rol no encontrado'
No sería necesario

2022-10-29 22:09 UTC, cumanachao commented on db/schema.rb
> +
Este cambio no va en este pr

2022-10-29 22:09 UTC, cumanachao commented on db/schema.rb
> +
Este cambio no va en este pr

2022-10-29 22:09 UTC, cumanachao commented on lib/tasks/generate_grades_cicles.rake
> +
Sacar línea extra al final del archivo.

2022-10-29 22:09 UTC, cumanachao commented on spec/factories/user_groups.rb
> +end
Este factory no es necesario para este pr

2022-10-29 22:09 UTC, cumanachao commented on lib/tasks/generate_grades_cicles.rake
> +    inicialPrimaria = Cicle.create!(name: 'Inicial/Primaria')
Usa snake_case:  `inicial_primaria = Cicle.create!(name: 'Inicial/Primaria')`

2022-10-29 22:09 UTC, cumanachao commented on lib/tasks/generate_grades_cicles.rake
> +desc "Generate grades and cicles(due to dependecies)"
Todo este archivo tiene 2 espacios más de indentación

2022-10-29 22:09 UTC, cumanachao commented on lib/tasks/generate_grades_cicles.rake
> +    Grade.create!(name: 'Nivel 0', cicle_id: maternal.id)
Cuando se hace un create no es necesario pasar el id:
`Grade.create!(name: 'Nivel 0', cicle: maternal)`

2022-10-29 22:14 UTC, cumanachao commented
Al nombre del PR ponele todo el título de la card, así cuando se mergee se puede saber qué era ese cambio desde git log mismo:

`BE-151: Listado de docentes`

2022-10-30 01:40 UTC, AnimA97 commented on app/serializers/group_serializer.rb
> +  def grade
Del grade solo precisamos el nombre, asi que asi es mas que suficiente para lo requerido.

2022-10-30 01:43 UTC, AnimA97 commented on config/locales/es.yml
> +    not_found: 'Rol no encontrado'
Este me salto como missing en un error que me salto y lo agregue, por las dudas lo dejo

2022-10-30 01:53 UTC, AnimA97 commented on spec/factories/user_groups.rb
> +end
Si es necesario, tengo que relacionar el usuario al grupo para los tests y no puedo sin el factory para la relacion entre ellos

2022-10-30 13:41 UTC, cumanachao requested changes

2022-10-30 13:41 UTC, cumanachao commented on app/serializers/group_serializer.rb
> +  def grade
REST se basa en la semántica de los modelos y de las relaciones.
Cuando se diseña una API, y más una REST (no como SOAP, por ejemplo), se intenta siempre no limitarse únicamente a lo que una implementación de un frontend en particular precisa en el momento.
Cuando se agregan relaciones de objetos se agrega todo el objeto. Si te fijas, lo que se hace es definir los atributos de los objetos en sí, y luego se agregan en las relaciones entre ellos. De esta manera se tiene cohesión en las respuestas; no hay un endpoint que retorna un grade de una manera y otro de otra. Cuando alguien del frontend ve que se retorna un grade ya sabe que adentro hay un name, por ejemplo.
Los serializers están pensados para que sean componibles y se pueda reutilizar, por eso está definido de esa manera con los métodos que se llaman igual que en ActiveRecord.
Yendo a lo práctico, si se precisa un botón al grade, por ejemplo, no lo pueden hacer porque no tienen el id para armar el link. 
Por esas razones está bueno en general tratar de no limitarse 100% a lo que una implementación en particular de un posible frontend precisa en este momento.

2022-10-30 13:41 UTC, cumanachao commented on config/locales/es.yml
> +    not_found: 'Rol no encontrado'
Te falla si haces `Role.find(:id)`.

2022-10-30 13:41 UTC, cumanachao commented on spec/factories/user_groups.rb
> +end
No me había dado cuenta que en el otro factory precisas crear un `user_group` porque tiene un rol.

2022-10-30 13:44 UTC, cumanachao commented
Estaba viendo que capaz es mejor usar la gema rolify en el modelo `user_group`. Sino terminamos implementando roles a mano con foreign keys hechas a mano y finds pero usando el modelo Role que es de la gema. Es como un medio camino ahí que no está bueno porque ya estamos usando la otra gema. Además la gema nos proporciona scopes generados (como el `.with_role()`) que nos pueden ser de utilidad luego.

También te quedaron cosas en el `schema.rb` que no son cambios de este ticket, ojo con eso que se puede armar quilombo luego con los schemas y las bases.

2022-10-30 14:02 UTC, AnimA97 commented on app/serializers/group_serializer.rb
> +  def grade
Ahora no es el caso que vayamos a precisar dicho boton y como se dijo ya mas de una vez no estamos para hacer gold plating, ese cambio es goldplating y esto lo precisan en front en para integrarlo

2022-10-30 14:05 UTC, AnimA97 commented
> Estaba viendo que capaz es mejor usar la gema rolify en el modelo `user_group`. Sino terminamos implementando roles a mano con foreign keys hechas a mano y finds pero usando el modelo Role que es de la gema. Es como un medio camino ahí que no está bueno porque ya estamos usando la otra gema. Además la gema nos proporciona scopes generados (como el `.with_role()`) que nos pueden ser de utilidad luego.
> 
> También te quedaron cosas en el `schema.rb` que no son cambios de este ticket, ojo con eso que se puede armar quilombo luego con los schemas y las bases.

Entiendo lo que decis guille, pero ya esta hecho de esta manera que funciona, no estamos en el punto de hacer goldplating y ponernos a rehacer cosas

2022-11-01 00:59 UTC, cumanachao commented
Ok, pero arregla lo del schema y el nombre del PR

2022-11-01 22:05 UTC, cumanachao approved these changes

2022-11-03 13:13 UTC, merged