(3)BE-200: Listar los estudiantes de uno de mis grupos
colegio-bilingue-cv/cb-api pull request #68
Opened 2022-11-03 18:46 UTC by Usuca

2022-11-03 21:25 UTC, cumanachao requested changes

2022-11-03 21:25 UTC, cumanachao commented on config/routes.rb
> +      resources :groups, only: [:index] do
Lo mismo que el otro pr, usa `scope` acá, asi no se define una ruta que no se usa

2022-11-03 21:25 UTC, cumanachao commented on app/serializers/group_and_students_serializer.rb
> +class GroupAndStudentsSerializer < Panko::Serializer
Un detalle nomas, le cambiaría el nombre a `GroupWithStudentsSerializer`

2022-11-03 21:25 UTC, cumanachao commented on app/serializers/group_and_students_serializer.rb
> +    object.grade.name
Usar el `delegate` de `name` a `grade` en el modelo

2022-11-04 16:21 UTC, Usuca commented on app/serializers/group_and_students_serializer.rb
> +    object.grade.name
En el modelo de group ya existe el delegate, lo tengo que poner en otro lado?

2022-11-06 22:21 UTC, cumanachao approved these changes

2022-11-06 22:21 UTC, cumanachao approved these changes

2022-11-06 22:22 UTC, merged