(3)BE-201: Listar mis grupos
colegio-bilingue-cv/cb-api pull request #70
Opened 2022-11-04 16:31 UTC by Usuca

2022-11-04 16:32 UTC, Usuca commented
Tendriamos que listar el rol que tiene en cada grupo?

2022-11-05 16:26 UTC, AnimA97 requested changes

2022-11-05 16:26 UTC, AnimA97 commented on app/controllers/api/me_controller.rb
> +    groups = current_user.groups
Los grupos que se tienen que poder ver aca no son todos los que tenga asignado el usuario, sino los que tiene asignado que son del anio actual en adelante

2022-11-05 21:20 UTC, cumanachao commented on app/controllers/api/me_controller.rb
> +    groups = current_user.groups
Recién Nico nos dijo que le retornemos todo y que en la pantalla esa de front hacen un `.filter()` para los grupos del año actual

2022-11-06 22:52 UTC, cumanachao approved these changes

2022-11-06 22:52 UTC, merged