(3)BE 152: Asignar grupo a usuario
colegio-bilingue-cv/cb-api pull request #73
Opened 2022-11-04 21:24 UTC by AnimA97

-UserGroups controller con creacion y destruccion de las associasiones
-Tests correspondiente
-Listado de docentes de cierto grupo en TeachersController
-Tests correspondiente

2022-11-05 22:19 UTC, cumanachao requested changes

2022-11-05 22:19 UTC, cumanachao commented on app/controllers/api/teachers_controller.rb
> +
Esto no va. No está bueno hacer dos cosas diferentes en un mismo action. Este es para traer todos los docentes. 
Si se precisa devolver los docentes de un grupo en particular se tiene que hacer en el controller de grupos.

2022-11-05 22:19 UTC, cumanachao commented on app/controllers/api/user_groups_controller.rb
> +    UserGroup.where(user_id: params[:user_id], group_id: params[:group_id], role_id: role_id).delete_all
Ojo que estás borrando todos los grupos de un usuario acá. Es lo que se quiere?

2022-11-05 22:19 UTC, cumanachao commented on app/controllers/api/user_groups_controller.rb
> +    render json: {}, status: :ok
Mejor poner `head :no_content`

2022-11-05 22:19 UTC, cumanachao commented on app/controllers/api/user_groups_controller.rb
> +end
Defini los params para los actions acá abajo como en los otros así es más fácil saber qué parámetros recibe cada acition.

2022-11-05 22:19 UTC, cumanachao commented on app/models/user_group.rb
> +  validates_uniqueness_of :user, :scope => [:group, :role_id]
Usa la otra sintaxis: `validates :user_id, uniqueness: { scope: [:group_id, :role_id] }`

2022-11-05 22:19 UTC, cumanachao commented on app/models/user_group.rb
> +  validates_uniqueness_of :group, :scope => [:user, :role_id]
Idem acá

2022-11-05 22:19 UTC, cumanachao commented on config/routes.rb
> +      get '/teachers', to: 'teachers#index'
Este action debería estar en el controller de grupos y no en el mismo action que el index de todos los teachers.

De igual manera eso sería otro ticket.

2022-11-07 18:39 UTC, AnimA97 commented on app/controllers/api/user_groups_controller.rb
> +    UserGroup.where(user_id: params[:user_id], group_id: params[:group_id], role_id: role_id).delete_all
Estoy borrando todas las instancias para (grupo, usuario, rol), que es una, no todos los grupos

2022-11-07 19:04 UTC, AnimA97 commented on config/routes.rb
> +      get '/teachers', to: 'teachers#index'
Lo pongo ahi y ya queda, como que no estamos en el  punto de hacer y borrar cosas, digo

2022-11-07 20:48 UTC, AnimA97 commented on config/routes.rb
> +      get '/teachers', to: 'teachers#index'
Ya lo puse en el controlador de grupos

2022-11-08 23:50 UTC, cumanachao approved these changes

2022-11-08 23:51 UTC, merged